import "./globals.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";
import { Roboto } from "next/font/google";
import QueryClientLayoutProvider from "./QueryClientProvider";
import 'swiper/css';
import 'swiper/css/navigation';

// const roboto = Roboto({
//   weight: ["100", "300", "500", "700"],
//   subsets: ["vietnamese"],
//   style: ["normal", "italic"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <meta httpEquiv="Cross-Origin-Opener-Policy" content="same-origin"></meta> */}
      {/* add link stop preload page */}
      <body suppressHydrationWarning={true}>
        <QueryClientLayoutProvider >
          {children}
          <ToastContainer />
        </QueryClientLayoutProvider>
      </body>
    </html>
  );
}
